### ISSUE TITLE
How do I get the game going? 

### ISSUE THREAD

**Issue by brookr** [NotFFTT/game#21]
Could the README maybe have a section on how to install and fire up the game for someone not familiar with it?

**Comment by brookr** [comment]
Thank you!!

**Comment by chloenott** [comment]
I don't remember closing this issue at all! I must've misclicked without realizing. Brannon updated the readme. If it's not enough detail, just let us know or message on slack. Server/host we're using might not be running 24-7, just poke me and I can turn it back on if don't want to go through the process of setting up your own droplet on digitalocean and executing `python3 server2.py`, or changing the address/port globals to localhost, etc.

ps: 24-7-365 server and something to make the game more accessible is on the todo list. I'm slightly worried it isn't completely impossible for someone to send down through the server to all the clients something maliciously pickled, so there are a few things to work through.
